name: "Code Scanning"

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every Thursday at 15:45 UTC.
on:
  push:
  schedule:
    - cron: '30 15 * * 5'

jobs:
  static-code:
    name: Static Code Analysis
    runs-on: macos-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Detekt Report
        run: ./gradlew detektReport detektMergeReport
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: build/reports/detekt.sarif
