name: Generate GH Pages
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  dokka:
    name: Build module and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'

      - name: Generate Dokka Page
        run: ./gradlew dokkaHtmlMultiModule

      - name: Publish Page
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: build/dokka/htmlMultiModule
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
