name: Generate GH Pages
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  dokka:
    name: Build module and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Generate Dokka Page
        run: ./gradlew dokkaHtmlMultiModule
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build/dokka/htmlMultiModule/"
