name: Pull Request Checks

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.github/*.yml'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  assemble:
    name: Assemble
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Build
        run: bash ./gradlew assemble

  test:
    name: Unit Tests
    runs-on: macos-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Run core tests
        run: bash ./gradlew :core:testDebugUnitTest

      - name: Run android-views tests
        run: bash ./gradlew :android:views:test

      - name: Code Coverage
        run: bash ./gradlew koverVerify
