name: Pull Request Checks

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.github/*.yml'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  assemble:
    name: Assemble
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Build
        run: bash ./gradlew assemble

  test:
    name: Unit Tests
    runs-on: macos-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Run allTests
        run: bash ./gradlew test

      - uses: actions/upload-artifact@v2.3.1
        if: failure()
        with:
          name: Unit test results
          path: ./**/build/reports/tests/
          if-no-files-found: ignore

      - name: Code Coverage
        run: bash ./gradlew koverVerify
