name: Pull Request Checks

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.github/*.yml'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  assemble:
    name: Assemble
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build
        run: bash ./gradlew assemble

  test:
    name: Unit Tests
    runs-on: macos-latest
    needs: assemble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Run core tests
        run: bash ./gradlew :core:testDebugUnitTest
      - name: Code Coverage
        run: bash ./gradlew koverVerify
